#!/data/data/com.termux/files/usr/bin/bash
SELF="$0"
while [ -L "$SELF" ]; do
    SELF="$(readlink "$SELF")"
done
BASE="$(cd "$(dirname "$SELF")" && pwd)"

if [ -z "$1" ]; then
    cat "$BASE/cmd.ls"
    exit 0
fi

CMD="$BASE/$1"
if [ -x "$CMD" ]; then
    exec "$CMD" "${@:2}"
else
    echo "unknown command: $1"
    echo
    cat "$BASE/cmd.ls"
fi
